[package]
name = "usable-dhbw"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Jannik Metz <@JannikMetz>"]
license = "MIT"
description = "A unofficial Typst Template for DHBW"
repository = "https://github.com/JannikMetz/usable-dhbw-typst-template"
keywords = ["dhbw", "thesis"]
categories = ["paper", "thesis", "report"]
exclude = ["template/main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"